nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/display-name: Virtual Clusters
    catalog.cattle.io/rancher-version: ">= v2.8.5"
    catalog.cattle.io/ui-extensions-version: ">= 2.0.0"
